### PR TITLE
Support relative roots for monorepos (#72)

### PR DESCRIPTION
**Pull request by jsmestad**
I did my best as a non-golang expert to implement #72 with as little code as possible.

## Feedback

It appears there is a step missing from the `CONTRIBUTING.md` file about how to get `lefthook` into the top of `$PATH`. I had to use `gem uninstall lefthook` and then `go install` to get the specs to run. However those also failed to pass because I am assuming there is more set up to do that I must have missed.

### CODE REVIEW

**Comment by Arkweid** [comment]
Cool! I'll check it soon.

**Comment by Arkweid** [comment]
Cool! I'll check it soon.

**Comment by jsmestad** [comment]
@Arkweid let me know. My team is eager to use this on our project 😉

**Comment by Arkweid** [comment]
Of course. I just usually have a time on weekends.

**Comment by jsmestad** [comment]
@Arkweid @dflock I found a bug with the root. It needed to be an absolute path. I have pushed the fix to this branch.

**Pull request merged**
