### PR TITLE
Add modular output

### PR DESCRIPTION
**Pull request by 0legovich**
Added the possibility of optional output of noisy information
Closes https://github.com/Arkweid/lefthook/issues/78

### CODE REVIEW

**Comment by Arkweid** [comment]
@0legovich Awesome! Will look at soon.

**Comment by 0legovich** [comment]
@Arkweid, what do you think about:
1) Explicitly specify the absence of output log: `output: false` (added in the current implementation).
2) In the current implementation, if there is no output log, information about the running command/script will still be displayed. For example `rubocop (SKIP. NO FILES FOR INSPECTION)` or `EXECUTE > rubocop`. Maybe it makes sense to add another output value `- stages`?
3) Is it correct not to show any message if the runner finished with a non-zero code status?

**Comment by Arkweid** [comment]
@0legovich 

> Explicitly specify the absence of output log: output: false (added in the current implementation).

It not very useful for me, but maybe others will find it as a good option in CI scenarios. So, okay.

> In the current implementation, if there is no output log, information about the running command/script will still be displayed. For example rubocop `(SKIP. NO FILES FOR INSPECTION)` or `EXECUTE > rubocop`. Maybe it makes sense to add another output value - `stages`?

Don't see a lot of sense for that. The best option is to associate this output with `failures` and `success` runners.

> Is it correct not to show any message if the runner finished with a non-zero code status?

If user set only `summary` - so not. Lets focus on most userful scenario. Most of devs want this:
```yml
output:
  - failures #(output from runners with exit code nonzero)
  - summary #(summary block)
```
They want to debug problems by log if something down and see a summary(tasks were completed).

**Comment by 0legovich** [comment]
@Arkweid 
> They want to debug problems by log if something down and see a summary(tasks were completed).

Maybe then it makes sense to go another way, for example:
```
skip_output:
  - meta
  - success
```

In this case, the user will always see the runners result regardless of whether there were failures or not. However, if there were failures, they will be output to log.

So I suggest removing the option to skip the output of `summary` and `failures` in the log.

**Comment by Arkweid** [comment]
@0legovich looks good for me.

**Comment by 0legovich** [comment]
@Arkweid thank you for your quick answers.

If we associate "EXECUTE > command_or_script_name" output with successful or unsuccessful runners, then the behavior of the application will change.

Before:
```
EXECUTE > command_or_script_name
<duration of the command>
Failure log
```

After:
```
<duration of the command>
EXECUTE > command_or_script_name
Failure log
```
Is this critical for this app? Any ideas?

**Comment by Arkweid** [comment]
@0legovich 
I don't think it's critical. It's acceptable behavior. 
Probably there needs some [spinner](https://github.com/cheggaaa/pb) element to inform users about lefthook still works. But it out of scope this task, so your choice.

**Comment by 0legovich** [comment]
@Arkweid Hi. The idea with the spinner seemed good to me. Please check the code.

**Comment by Arkweid** [comment]
@0legovich take a look at `run_windows.go`. It a file for windows ecosystem compile. Copy existed code into.
`run` and `run_windows` mostly the same. But Windows haven't `pty` interface. 
We cannot easily synchronize the output, but it okay for windows :)

**Comment by 0legovich** [comment]
@Arkweid, thank you. I added this functionality for the Windows ecosystem.

**Comment by Arkweid** [comment]
@0legovich I have tested PR for discourse example(my OS is Ubuntu 18) and got this output:
```
Lefthook v0.7.2
RUNNING HOOKS GROUP: pre-commit

echo-skip1 (SKIP. NO FILES FOR INSPECTION)

echo-skip2 (SKIP. NO FILES FOR INSPECTION)

echo-skip3 (SKIP. NO FILES FOR INSPECTION)

  EXECUTE > eslint-assets
 read /dev/ptmx: input/output error

  EXECUTE > eslint-assets-tests
 read /dev/ptmx: input/output error

  EXECUTE > eslint-plugins-assets
 read /dev/ptmx: input/output error

  EXECUTE > eslint-plugins-test
 read /dev/ptmx: input/output error

  EXECUTE > eslint-test
 read /dev/ptmx: input/output error

  EXECUTE > prettier
 read /dev/ptmx: input/output error

SUMMARY: (done in 15.13 seconds)
🥊  eslint-assets
🥊  eslint-assets-tests
🥊  eslint-plugins-assets
🥊  eslint-plugins-test
🥊  eslint-test
🥊  prettier

```
Probably this one is root of problem:
https://github.com/Arkweid/lefthook/pull/130/files#diff-e540b5efa4ce165399814e0fc4016fa4R267

**Comment by 0legovich** [comment]
@Arkweid Thank you for your detailed comment.
I fixed this behavior.

**Comment by Arkweid** [comment]
Will look at soon.

**Comment by Arkweid** [comment]
Sorry for so long @0legovich 
Looks fine! Merged :)

**Pull request merged**
